### ISSUE TITLE
[Question] Can't follow last instruction

### ISSUE THREAD

**Issue by systox** [radugrecu97/steamdeck-moonlight-shortcut#1]
I can't complete the final instruction. I receive the error: no such file or directory. The file is there though in that directory. Any help appreciated.

 
(deck@steamdeck steamdeck-moonlight-shortcut)$ chmod +x create-shortcuts.sh
(deck@steamdeck steamdeck-moonlight-shortcut)$ ./chmod create-shortcuts.sh
bash: ./chmod: No such file or directory
(127)(deck@steamdeck steamdeck-moonlight-shortcut)$

**Comment by systox** [comment]
nvm, got around it by righclicking the script and selecting run in konsole. It didn't pick up any of my applications though. will continue troubleshooting.

**Comment by radugrecu97** [comment]
Yes, sorry for the trouble. I know there's some instructions I forgot

**Comment by systox** [comment]
Thanks Radu, no sorry necessary. I’m just new to Linux and its syntax. Got it working successfully soon after. Merci for the great program.
